### PR TITLE
edit pattern

### PR DESCRIPTION
**Pull request by D0rG**
It will be faster, but will not be able to see more than one space between the letters.

### CODE REVIEW

**Comment by Kladmen228** [comment]
Are u curiously men? It was bed(krovat’) fix

**Comment by D0rG** [comment]
No, that's a good enough change

**Comment by Kladmen228** [comment]
You are autistic, don’t google translater

**Comment by D0rG** [comment]
I am not Google translater 

> You are autistic, don’t google translater

**Comment by D0rG** [comment]
Vladelec pYdoor, udalyaet messages

**Pull request closed without merging**
